### ISSUE TITLE
주기적으로 RESTART 하였을때 주기적인 알림 해제 요청

### ISSUE THREAD

**Issue by spamuse** [acidpop/xpebot#12]
3시간마다 RESTART를 하다보니 3시간에 한번씩 알림 문자가 뜨는것을 없앨수는 없는건가요??

**Comment by acidpop** [comment]
xpebot 시작시 보내는 알람 메시지는 이미 삭제 되어 있습니다.

main.py 파일이 제대로 업데이트 되는지 확인해보세요

**Comment by spamuse** [comment]
git pulll 하니 해결되네요,,,,그럼 수고하세요,,

**Comment by acidpop** [comment]
넵 소스는 항상 최신으로 유지 해주세요~!
