### ISSUE TITLE
fatal: Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by iruyanka** [acidpop/xpebot#16]
git clone "https://github.com/acidpop/xpebot"
Cloning into 'xpebot'...
fatal: Unable to find remote helper for 'https'

기존 설치된걸 git pull 로 업데이트 하려니 안 되서 재설치하려해도 안 되네요.

https 가 아닌 다른 경로가 필요한건지 잘 모르겠습니다.

**Comment by acidpop** [comment]
음....시험 삼아 다른 시스템에서 

git clone "https://github.com/acidpop/xpebot"

을 해봤는데 잘 받아집니다.

curl https://github.com

명령으로 HTML 소스가 보이는지 확인해 보세요

만약 연결이 안된다면 해당 시스템의 DNS 가 제대로 안되어 있거나
인터넷 연결이 잘 안되는 상황일 수 있습니다.

**Comment by iruyanka** [comment]
html 소스는 잘 보입니다. 인터넷 연결은 문제 없이 잘 됩니다.
항시 시딩 중이라서요.

통합대기지수에 오존, 자외선 같은것도 추가 되어도 괜찮을듯 합니다.

https://search.naver.com/search.naver?where=nexearch&query=%EC%98%A4%EC%A1%B4&sm=tab_drt&ie=utf8

**Comment by acidpop** [comment]
다른 github 소스도 받아 지는지 확인 부탁드립니다.

오존/자외선은 다음 버전에 추가해 보도록 하겠습니다. ^^

**Comment by iruyanka** [comment]
/usr/local/flexget/env/bin/pip install --upgrade flexget

flexget 사용중인데 flexget 은 버전 업데이트가 매우 잦습니다.
rss 로 github 업데이트 내역이 뜨면 바로 업데이트하는데 이건 잘 됩니다.

github 주소를 따는게 아니라 그런건지 혹은 github 와 연관성이 없는건지는 잘 모르겠습니다.

**Comment by acidpop** [comment]
pip 와 github 가 같은 저장소를 쓰는지는 잘 모르겠네요.

git clone "https://github.com/nickoala/telepot"

위에건 telepot 의 git 소스인데 다른 디렉토리에 가셔서

받아 지는지 한번 확인 해주세요

**Comment by iruyanka** [comment]
Cloning into 'telepot'...
fatal: Unable to find remote helper for 'https'

안 되네요. 뭐가 문제인지 모르겠습니다.

**Comment by acidpop** [comment]
흠.. DSM 몇 버전 사용하시나요?

**Comment by iruyanka** [comment]
DSM 5.2-5967 Update 1 사용중입니다.

**Comment by acidpop** [comment]
https 를 연결을 못하는 문제로 보이는데 도무지 알수가 없네요.

Clone or Download 메뉴를 이용하셔서 ZIP 으로 받으신 다음 
압축을 풀어서 사용하셔야 할것 같습니다.

**Comment by iruyanka** [comment]
git clone "git://github.com/acidpop/xpebot"
으로 넣으니 설치가 됩니다.

https 연결문제 같은데 도무지 방법이 없네요.

우선은 이렇게 사용하면 되는데 업데이트 명령어는 어떻게 해야할런지요.

git pull 도 같은 오류가 발생해서요.

"git://github.com/acidpop/xpebot"

요 주소를 넣어 업데이트 하려면 명령어를 뭐라고 넣어야 하나요?

**Comment by iruyanka** [comment]
./bot.sh start
-ash: ./bot.sh: Permission denied

설치해놓으니 이제는 이러고 있네요. 전에는 안 그랬는데 속성에서 0755 로 체크를 해줘도 안 됩니다.

**Comment by acidpop** [comment]
패키지 센터에서 Git Server 버전이 2.8 일때 발생하는 문제 인거 같습니다.

Permission denied 는 왜 그런지 확인 해볼께요

**Comment by acidpop** [comment]
bash 파일에 실행 권한이 없어서 발생한 문제인걸로 확인 되었습니다.
현재 github 에는 실행 권한이 포함되어 있습니다.
