### ISSUE TITLE
BotManager.py 권한 문제 인듯한데...

### ISSUE THREAD

**Issue by iruyanka** [acidpop/xpebot#17]
```
server> cd /var/services/homes/username/xpebot
server> /usr/local/git/bin/git pull
Updating 18fcae9..39dbe1f
error: Your local changes to the following files would be overwritten by merge:
        BotManager.py
Please, commit your changes or stash them before you can merge.
Aborting
```

http://blog.acidpop.kr/228
이렇게 변경을하지 않고, "/usr/local/git/bin/git pull" 이렇게하면 업데이트는 되는듯 합니다.

헌데, BotManager.py 를 어떻게 하라는건지 모르겠네요. 권한관련 문제인듯한데...

**Comment by acidpop** [comment]
BotManager.py 가 권한이 수정 되어서 원본이랑 다른것으로 인식 하는것 같습니다.

git checkout -- BotManager.py
이 명령 진행 하신 다음

git pull 을 이용해서 업데이트 해보세요

**Comment by iruyanka** [comment]
아, 알려주신대로하니 업데이트 됩니다. 고맙습니다.
