### ISSUE TITLE
/torkim 의 .torrent 파일 관련 버그

### ISSUE THREAD

**Issue by iruyanka** [acidpop/xpebot#19]
WATCH_DIR 는 정상적으로 설정되어 있습니다.

/torrentsearch 로 다운받을때는 잘 작동합니다.

/torkim 은 /var/services/homes/username/xpebot 에 .torrent 파일이 다운로드 됩니다.

/torkim 이 뭘까 궁금해서 보니 선택할 수 있는 파일 목록이 키보드가 아닌 대화창(?)에
직접 뜨는듯해서 깔끔하고 좋아 보입니다. 목록에서 여러개 다운로드도 되는듯 하구요.

다만, 씨앗파일이 WATCH_DIR에 다운로드 되지 않아 파일의 다운로드가 안 됩니다.

**Comment by iruyanka** [comment]
아, 이게 인라인 키보드인가 보군요?ㅎ

**Comment by iruyanka** [comment]
추가로 하나 더...

이건 버그인지 원래 그런건지 모르겠습니다.

/torkim 검색결과가 뜬 상태에서 /cancel 로 모드 취소가
되었음에도 선택하면 다운로드가 됩니다.

/gettorrent 모드에서도 마찬가지 입니다.

**Comment by iruyanka** [comment]
음...여태 /torrentsearch 와 /torkim 의 이용방법을 제가 잘 몰랐습니다.

마그넷 과 씨앗파일 서로 다른 방식이군요.

.torrent 씨앗 파일을 왓치폴더에 다운받아 다운로드 스테이션에 거는...ㅎ

```
# Torrent Watch Directory Path
WATCH_DIR       = /volmue1/download/µTorrent
```

µTorrent 의 µ 를 인식 못 해서 생기는 문제인지도 모르겠습니다.

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 18: ordinal not in range(128)
```

이렇게 에러 메시지가 뜨는걸로 봐서는 뒤의 µ 를 인식 못하는것 같네요.

다른 경로에서는 다운로드가 잘 됩니다. 여태 씨앗이 엉뚱한데로 받아져서 안 되는거 였네요.

**Comment by acidpop** [comment]
/torkim 과 /gettorrent 명령이 인라인 키보드를 사용합니다.

인라인 키보드는 각각의 버튼마다 콜백을 지정 할수가 있어서 그렇게 사용을 하고
/cancel 은 인라인 키보드에는 적용 되지 않습니다.

그리고 watch_dir 은 유니코드가 포함된 디렉토리는 고려를 안했네요 ^^;;

수정 해두었습니다.

**Comment by iruyanka** [comment]
네. 다운로드 잘 됩니다. 고맙습니다.
