### ISSUE TITLE
다운로드스테이션 토렌트 파일 추가시 오류

### ISSUE THREAD

**Issue by hemapresso** [acidpop/xpebot#23]
xpebot 적용해보다 아래와 같이 다운로드스테이션에 토렌트 파일이 추가될때 오류가 발생합니다.

오류로그는 아래와 같습니다.

2016-10-22 03:06:31 [ERROR] download_db_timer Exception : Traceback (most recent call last):
  File "/volume1/homes/admin/xpebot/dsdownload.py", line 390, in download_db_timer
    self.bot.sendMessage(self.chat_id, msg, parse_mode='Markdown')
  File "/usr/lib/python2.7/site-packages/telepot/**init**.py", line 409, in sendMessage
    return self._api_request('sendMessage', _rectify(p))
  File "/usr/lib/python2.7/site-packages/telepot/__init__.py", line 398, in _api_request
    return api.request((self._token, method, params, files), **kwargs)
  File "/usr/lib/python2.7/site-packages/telepot/api.py", line 131, in request
    return _parse(r)
  File "/usr/lib/python2.7/site-packages/telepot/api.py", line 126, in _parse
    raise exception.TelegramError(description, error_code, data)
TelegramError: (u'Bad Request: Wrong message entity: Wrong URL host', 400, {u'error_code': 400, u'ok': False, u'description': u'Bad Request: Wrong message entity: Wrong URL host'})

텔레그램에서 메세지를 보내는 과정에서 URL 잘못되고 있는것 같은데, 혹시 어떤부분을 확인해야할지 조언부탁드립니다. 감사합니다.

**Comment by hemapresso** [comment]
^^;; 이게 뭐라고 삽질끝에 원인파악했습니다.

결국 토렌트 제목에 일부 특수문자때문에 "Wrong URL host"라고 나오는 걸 알았내요;;

음.. 파이썬은 잘 몰르긴하지만, 

일단 정규식으로 특수문자 제거했더니 정상적으로 메세지가 전송되었습니다.

dsdownload.py 에서 아래와 같이 수정했습니다.

import re
tor_name = re.sub('[[]=#/?:$}]', '', tor_name)

더 좋은 방법으로 수정 부탁드립니다.

늘 감사합니다~^^

**Comment by acidpop** [comment]
모든 문자열이 utf8 로 작동을 하는데 어떤 특수 문자 때문에 이러는걸까요?

뭔가 []=#/?:$} 여기 포함된 문자랑 조합이 되었을때 발생하는거 같은데..

[]=#/?:$} 이 문자를 bot 에서 보내보면 잘 보내지더라구요.

해당 토렌트 제목 일부분이라도 알수 있을까요?

**Comment by hemapresso** [comment]
%5BKBS N Sports%5D The 레전드.E05.홈런본능 괴력의 거포%2C 박병호.HDTV.H264.720p-SolKae™.avi.torrent
%5BKBS N Sports%5D The 레전드.E03.조선 4번 타자의 꿈%2C 이대호.HDTV.H264.720p-SolKae™.avi

제가 테스트해 본 토렌트 파일들입니다.

아마 메세지를 보낼때에는,
[KBS N Sports] The 레전드.E05.홈런본능 괴력의 거포, 박병호.HDTV.H264.720p-SolKae™.avi.torrent
[KBS N Sports] The 레전드.E03.조선 4번 타자의 꿈, 이대호.HDTV.H264.720p-SolKae™.avi
결국 이런 텍스트로 요청하게 되는 것 같던데, 

텔레그램 API에서 응답이 잘못된 url (400) 이라고 오는걸 봐서는 [] 이 특수문자가 문제가 아닐까 싶내요..

**Comment by acidpop** [comment]
주신 예제를 보니 원인 파악이 금방 됐네요 ^^;;
제가 DownloadStation 메시지를 보낼때 Telegram 의 MarkDown 형태로 보내게 되는데
이때 [] 중괄호가 MarkDown 문법에 걸려서 문제가 발생 하네요...

현재 버전은 _ 언더바와 \* 문자만 MarkDown 문법에 걸리지 않도록 수정했는데 MarkDown 에 사용하는 문자를 모두 보낼 수 있도록 수정 해야겠습니다.

버그 리포트 감사합니다. ^^

**Comment by acidpop** [comment]
해당 이슈가 해결 된 버전이 업데이트 되었습니다.
