### ISSUE TITLE
DSM 6.0  이상 봇 중복 실행 가능

### ISSUE THREAD

**Issue by acidpop** [acidpop/xpebot#24]
DSM 6.0 이상에서 xpebot 이 중복 실행 될수 있는 버그가 발견 되었습니다.

bot.sh 에서 ps 명령어를 이용해 봇을 중지 하거나 체크 하는데 

DSM 6.0 에서는 ps w 명령이 아닌 ps -ef 명령등을 이용해서 봇 작동을 체크 해야 합니다.

해당 문제에 관해 DSM 6.0 사용자 분께서는 일단 사용에 유의해 주시기 바랍니다.

**Comment by luna1474** [comment]
PID=($(ps -ef | grep xpebot| grep -v "grep" | awk '{print $2}'))

PID체크 부분이 문제가 있었네요
저 명령어는 감시 스크립트에서 찾아와서 print $2로 숫자만 바꿨더니 pid정보가
root에서 pid값으로 바꼈습니다 (grep한 값이 root xxxx 으로 나오는데 root 값을 가져오게 된게 원인이였던거 같습니다)
6.0사용자 분들은 이렇게 사용하면 문제없을듯 합니다

**Comment by acidpop** [comment]
DSM 6.x 에서는 ps -ef 명령을 사용하다 보니
기존 5.2에서 ps w 명령 결과와는 다르게 출력이 되어서
뒤쪽 awk 명령이 잘못 작동 하는 문제가 있더군요.
현재 조금 더 테스트 중입니다.

**Comment by acidpop** [comment]
bot.sh 를 DSM 6.0 전용으로 하나 더 추가 하였습니다.
