### ISSUE TITLE
12시가 되면 봇이 사라지는 현상 (신데렐라?)

### ISSUE THREAD

**Issue by luna1474** [acidpop/xpebot#25]
root     30827 29610  0 00:30 pts/14   00:00:00 grep --color=auto python

전날 11시에 작동되는거 확인했지만 12시가 되니까 봇이 사라지는 것 같습니다
-------------------------------------
root     20068 20040  0 09:11 pts/10   00:00:00 grep --color=auto python
아침에 다시 확인해보니까 또 가출했네요
02:53에 작동했지만 03:13에 있었떤 알림은 안왔던 것으로 보아 3시에 무슨 일이 있었나봅니다

**Comment by acidpop** [comment]
해당 이슈는 아직 정확한 원인이 확인되지 않고 있습니다.

로그 상으로는 어디선가 kill 또는 pkill 명령을 이용해서 강제 종료 시켜버리는 케이스로 보입니다.

**Comment by acidpop** [comment]
SIGTERM 시그널을 무시 하도록 변경 하였습니다.
