### ISSUE TITLE
gettfreeca 사용시 다운로드 경로가 잘못된듯합니다.

### ISSUE THREAD

**Issue by zenc** [acidpop/xpebot#27]
Torrentkim 사용시에는 설정값에서 지정한 WATCH_DIR 로 다운로드 되는데,
gettfreea 의 경우 계정디렉으로 다운로드 됩니다.
참고하시기 바랍니다.

더불어 덕분에 편하게 잘 쓰고 있습니다.
감사합니다~

**Comment by acidpop** [comment]
WATCH_DIR 로 다운로드 하는 기능은 /tfreeca 입니다.

/gettfreeca 는 텔레그램으로 토렌트 파일을 전송 해주는 기능이에요
