### ISSUE TITLE
기능 요청 토렌트 다운로드 알림시 포스터 첨부

### ISSUE THREAD

**Issue by chsyong** [acidpop/xpebot#28]
신규 다운로드시  포스터도 첨부해서 알림 기능 가능할까요?

**Comment by acidpop** [comment]
포스터라 하시면 영화나 드라마 들의 그 이미지를 말씀하시는 건가요?

각 토렌트 사이트에서 해당 토렌트 게시물에 지정된 포스터 태그가 있다면 가능 하겠지만

토렌트 라는게 꼭 미디어 일수는 없으니 불가능 하지 싶습니다.

**Comment by chsyong** [comment]
네 말씀하신 그 기능이 맞는데 아쉽네요 ^^;

**Comment by chsyong** [comment]
만들어주신 봇 넘 잘 사용하고 잇습니다~ 감사합니다(__)
