### ISSUE TITLE
다운로드 스테이션의 다운로드 활성화시 알림이 메인 사용자에게만 옵니다.

### ISSUE THREAD

**Issue by chsyong** [acidpop/xpebot#30]
전에는 안그랬던거 같은데 
NOTY_CHAT_ID, VALID_USER 설정이 두개가 잇는데
VALID_USER 에 등록된 사용자는 검색 다운로드 등을 할 수 잇지만

실제로 다운로드가 시작되엇는지 또는 완료되었는지 알림은 NOTY_CHAT_ID 이쪽으로 밖에 알림이 안가더라구요.
NOTY_CHAT_ID 에 ,로 구분 등록 가능하게 하고 등록된 만큼 메시지 뿌려주는게 어떨까요....?

**Comment by acidpop** [comment]
원래 NOTY_CHAT_ID 에 등록된 ID 하나에만 알림을 보내도록 되어 있구요
여러명이 알림을 받고 싶으시다면 그룹 채팅방을 만들어서 그룹 채팅방 ID 를 NOTY_CHAT_ID 에 등록 해주시면 됩니다.

원하시는 기능은 추후에 시간이 되면 검토해보겠습니다.

**Comment by acidpop** [comment]
환경설정 파일에 NOTY_CHAT_ID 에 여러명을 등록 할 수 있도록 변경 하였습니다.
