### ISSUE TITLE
새로 봇 추가하려면 어떻게 하나요?

### ISSUE THREAD

**Issue by lth1436** [acidpop/xpebot#31]
좋은 봇 감사드립니다.

새로운 .py 파일을 추가 및 설정하려면 어떻게 진행해야하는지 알고싶습니다

**Comment by acidpop** [comment]
안녕하세요
해당 방법은 python 에 관해서 학습을 하시면 되고 
xpebot 소스를 조금만 분석해 보시면 바로 보일거에요.
봇 명령들은 BotManager.py 파일에 존재 하고 각각 명령에 따라 다른 py 파일들을 사용합니다.
